# Generated by Django 6.0.1 on 2026-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='information', verbose_name='Imagen')),
                ('resume', models.TextField(blank=True, verbose_name='Resumen')),
                ('desc_contact', models.TextField(blank=True, verbose_name='Resumen de contacto')),
                ('cell', models.IntegerField(verbose_name='Celular')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('honorarios', models.CharField(max_length=200, verbose_name='Honorarios')),
            ],
        ),
    ]
