# Generated by Django 6.0.1 on 2026-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoPersonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cell',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
