# Generated by Django 6.0.1 on 2026-03-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoPersonal', '0002_alter_information_cell_alter_information_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portadaImage', models.ImageField(blank=True, null=True, upload_to='backgorund', verbose_name='Fondo de portada')),
                ('acercaDeImage', models.ImageField(blank=True, null=True, upload_to='backgorund', verbose_name='Fondo de Acerca de')),
                ('portafolioImage', models.ImageField(blank=True, null=True, upload_to='backgorund', verbose_name='Fondo de portafolio')),
                ('contactImage', models.ImageField(blank=True, null=True, upload_to='backgorund', verbose_name='Fondo de contacto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'informacion', 'verbose_name_plural': 'informacion'},
        ),
    ]
